version: '3'

services:
  nginx-container:
    image: ghcr.io/oscarzhou-portainer/httpd:latest
    container_name: nginx-cont
    ports:
      - "${PORT:-81}:80"
    labels:
      - branch="main"
      - version=5
