version: '3'

services:
    
  nginx-cont:
    env_file:
      "stack.env"
    image: ghcr.io/oscarzhou-portainer/portainer-demo/nginx:latest
    container_name: "${CONTAINER_NAME}"
    ports:
      - "${PORT:-81}:80"
