apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-1
  template:
    metadata:
      labels:
        app: httpd-1
    spec:
      containers:
        - name: httpd
          image: registry.internal.services.oscarchou.com/httpd:latest
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-1
spec:
  selector:
    app: httpd-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-2
  template:
    metadata:
      labels:
        app: httpd-2
    spec:
      containers:
        - name: httpd
          image: ghcr.io/oscarzhou-portainer/httpd:latest
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-2
spec:
  selector:
    app: httpd-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
