version: '3'
services:
 large-app:
  image: 6261998/alpine:latest
  volumes:
      - ./html:/home/html
  tty: true
  stdin_open: true
  environment:
   - ${ENV:-default}=novigrad1
   - ${ENV2:-default2}=111
   - ${ENV3:-default3}=esm
   - MY_JSON={"key":value}

# inject env var to reproduce: MY_ENV=null
